### ISSUE TITLE
sorgu @question

### ISSUE THREAD

**Issue by gitmuhammedalbayrak** [mehmet-zahid/discord-bot#1]
MAKEFILE dosyasının docker image içinde bulunması efektif mi?

**Comment by mehmet-zahid** [comment]
Docker image i içinde bulunması manasız. Yani proje yapısına göre değişkenlik gösterebilir. Ama makefile bazı komutları kısaltmak için var sanırım.

**Comment by mehmet-zahid** [comment]
there is no question about this. closed .
